# Generated by Django 6.0.2 on 2026-05-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('diagnosis', models.CharField(max_length=200)),
                ('previous_admissions_6m', models.IntegerField()),
                ('previous_readmissions_1y', models.IntegerField()),
                ('length_of_stay', models.IntegerField()),
                ('severity_score', models.FloatField()),
                ('hba1c_level', models.FloatField()),
                ('creatinine_level', models.FloatField()),
                ('hemoglobin_level', models.FloatField()),
                ('average_systolic_bp', models.FloatField()),
                ('medication_adherence_score', models.FloatField()),
                ('probability_score', models.FloatField(default=0)),
                ('risk_level', models.CharField(default='Low', max_length=50)),
                ('prediction', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
