# Generated by Django 6.0.2 on 2026-05-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='admission_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='chronic_disease_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='comorbidity_index',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='discharge_disposition',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='followup_appointment_scheduled',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='high_risk_medication_flag',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='icu_stay_flag',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='insurance_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='medication_change_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='number_of_medications',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='primary_diagnosis_group',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='socioeconomic_risk_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='time_since_last_discharge',
            field=models.IntegerField(default=0),
        ),
    ]
